"""Quaternary Verdict — four-value evaluation for agentic loops."""

from .core import (
    CheckResult,
    ComputeNeed,
    EvidenceNeed,
    Needed,
    Verdict,
    iff,
    maybe,
    no,
    yes,
)
from .qict import (
    AuditResult,
    CandidateDisposition,
    ControllerAction,
    ControllerEvent,
    ControllerEventKind,
    ControllerState,
    ControllerStatus,
    DependencyRecord,
    EvaluationReceipt,
    EventReceipt,
    Lease,
    LeaseKind,
    QICTConfig,
    QICTController,
    ResolutionOutcome,
    TransitionReceipt,
    audit_trace,
    rank,
)
from .runner import LoopOutcome, run

__all__ = [
    "AuditResult",
    "CandidateDisposition",
    "CheckResult",
    "ComputeNeed",
    "ControllerAction",
    "ControllerEvent",
    "ControllerEventKind",
    "ControllerState",
    "ControllerStatus",
    "DependencyRecord",
    "EvaluationReceipt",
    "EventReceipt",
    "EvidenceNeed",
    "Lease",
    "LeaseKind",
    "LoopOutcome",
    "Needed",
    "QICTConfig",
    "QICTController",
    "ResolutionOutcome",
    "TransitionReceipt",
    "Verdict",
    "audit_trace",
    "iff",
    "maybe",
    "no",
    "rank",
    "run",
    "yes",
]

__version__ = "0.2.0"
